transmission:
    env: ENC[AES256_GCM,data:883kDOImh6ER6m8DJ9vqA2canngKDyY=,iv:CaLuArc0VJtAWoXFOyH6g/GYdwoYRS2Ne6av6KE3AeQ=,tag:HK2oWn9hHP5frjO88E1xHw==,type:str]
grafana:
    admin_password: ENC[AES256_GCM,data:e5uYzuGhSNpdP1RiG8Eqd78Vl+fkG3SGOixU06c8gw==,iv:5cmZFcXjJLiS+5xVs+0cWQWg73wfkJCXuFqLDLbhNUA=,tag:v2nMDv1b++0e6WnBiv0IJg==,type:str]
neo_user:
    hashed_password: ENC[AES256_GCM,data:SP3laQ9sjhktz1q/HBFODz2tqO5PnEorBavzU0hJKD57D2GOKJJh1xm6MQSbBLFxzkbEvSTu8Wt2PlYs154FqoQWI+ZEfWkmbH7JxcAdkvivoiav1adcFWwlQbx8i77KWbG3JMhVJ6pkiw==,iv:Oue/kFPOfTbyt9/+/sGzSikoubye43OZZJrdE3q5pMc=,tag:cL7UnEVvdMNL1flYT4OTjg==,type:str]
cloudflare:
    tunnel_token: ENC[AES256_GCM,data:Yb9U20ws3E399qMuJ5YB+4uscg3Sjd2+ru10VhLaXzVXJI3/yL/Y2gqZrIhKtTC5/yKrYn5AsKfgbu7b7nvZzUk/yStXZ+K394OZPy3XOi65Lrh7U3Gg+e4A4O4p83XesA4O/XW7NJdJEnHLFbUU+gC+gsscCDYufK2W/g2yLDAjPwHdaAxPVeC+4n2JO7IC4LULmMdRov2PqI4j0xVFsLn7Kctt8gD8t6YEiW36afvWT3x+tdxu1g==,iv:W53nUZttRC1SuNBJJSscDMIBxkWjoKTY8XcW+fICw+8=,tag:UEmZfURhk0asu6c+bCsnSg==,type:str]
code_server:
    env: ENC[AES256_GCM,data:HCovqp+w1YpOgKWIaosodYhz1ZrvyqgWxx5Sb+S38g==,iv:jQabxcst83gV96UDUs3giztQOh1uTsj/fhQ3t30vLlY=,tag:L+BL3EcPBlKXvDLWNHbpwg==,type:str]
sops:
    age:
        - recipient: age1r4sj55qcuynj336j6ef0vd2ushgrjfxexw65fgaa0wyj6r47nsfqu96udq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWQ3RoRU96MW53NThTbDVy
            Nko0NUh0ZkpRM0pYYXhMOThpSndQdWlaZVJZCkZEUzNPMk8vNUpHUTNBdDBQZFVM
            TzFUMTQ2SGd6emlNZkxBWk9MMnR6ak0KLS0tIFphanR3VzFBT2QxNUozV1VKRnlh
            eFdsREo2Y1ZnL3dDVU13M2VlcXIwcDQKZhISYqE2Y1xxEcwJlekZcxN6Ft/8efTH
            A1CS+WRjrn3Ea6RDmK+aahyR48y6AaOTxBBabeyo7v+H5bmAj5NRDg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-07T09:46:18Z"
    mac: ENC[AES256_GCM,data:xv8tjv5LcoCesaJd/CO96ggpYHn6QaiYR5hS3rh4/hFqQq4PkVKtzshPjqEsAdfnrmYOp7m/rh3Ay7vAtnynpQqUXtOz47+SWLJoVaVYtrBJh/X8EXjKjX7EWTuXSd8ZBWECsJDAulx/S2DdmWUFgBwHnlu5j2I8pznhi26jK5w=,iv:jz5y6DWU9qQ/Gb1TGUKX1KLef4ZV+69w+Tlbn2bQ9Lo=,tag:koWWsvv02xnwhRKuUEw+/g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
