syncthing:
    gui_password: ENC[AES256_GCM,data:bUKuILfNJHlXQjmd/ys8SFF5ng4FS8ZVVA==,iv:U+DC9CUlSyAeVM1lxKylfsLzoTIBv2wBCbjhO1qelJk=,tag:DqNwSj2FACdE9PndC/xE2w==,type:str]
transmission:
    env: ENC[AES256_GCM,data:883kDOImh6ER6m8DJ9vqA2canngKDyY=,iv:CaLuArc0VJtAWoXFOyH6g/GYdwoYRS2Ne6av6KE3AeQ=,tag:HK2oWn9hHP5frjO88E1xHw==,type:str]
grafana:
    admin_password: ENC[AES256_GCM,data:Ef1mC10k4uAKT2Xs0a12UA==,iv:FdU8KLaGKBhONg5ZQub8e67m3kF6/tW9Ow+mbjaZxIU=,tag:1JS9dFNHJ/hZLSBZ6z5nvQ==,type:str]
neo_user:
    hashed_password: ENC[AES256_GCM,data:SP3laQ9sjhktz1q/HBFODz2tqO5PnEorBavzU0hJKD57D2GOKJJh1xm6MQSbBLFxzkbEvSTu8Wt2PlYs154FqoQWI+ZEfWkmbH7JxcAdkvivoiav1adcFWwlQbx8i77KWbG3JMhVJ6pkiw==,iv:Oue/kFPOfTbyt9/+/sGzSikoubye43OZZJrdE3q5pMc=,tag:cL7UnEVvdMNL1flYT4OTjg==,type:str]
sops:
    age:
        - recipient: age1r4sj55qcuynj336j6ef0vd2ushgrjfxexw65fgaa0wyj6r47nsfqu96udq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWQ3RoRU96MW53NThTbDVy
            Nko0NUh0ZkpRM0pYYXhMOThpSndQdWlaZVJZCkZEUzNPMk8vNUpHUTNBdDBQZFVM
            TzFUMTQ2SGd6emlNZkxBWk9MMnR6ak0KLS0tIFphanR3VzFBT2QxNUozV1VKRnlh
            eFdsREo2Y1ZnL3dDVU13M2VlcXIwcDQKZhISYqE2Y1xxEcwJlekZcxN6Ft/8efTH
            A1CS+WRjrn3Ea6RDmK+aahyR48y6AaOTxBBabeyo7v+H5bmAj5NRDg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-15T09:22:21Z"
    mac: ENC[AES256_GCM,data:FRxJzCEgNE6o4vwE1WTEsPawIQVE6FQyEz/wmBzn+ejo6Efhny2K93rDr2ZKdgrCuFVJbjU8NYvedkPreUN7V71kzuEWQlzY+KtzqGgF5QYIAgiMA+yDocLTiTFcI4wDmWGZc3FQSReSxG6EjIUe3DprOqMCSFoNRk3yzpFO+G4=,iv:PfDxielf1h0PTKoREI+K2BsAWBSdhd2SAqQxO77pMyc=,tag:AY3buL8eiNgwzg5cuZkmMQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
